use std::path::Path;

use anyhow::{Context, Result};
use serde::{Deserialize, Serialize};

use crate::application::port::github_client::{GitHubIssueDetail, ReviewThread};
use crate::domain::author_association::TrustedAssociations;

// === Input directory management ===

/// `.cupola/inputs/` ディレクトリを削除してから再作成する。
///
/// # Preconditions
/// - `worktree_path` はワークツリーのルートパスである
///
/// # Postconditions
/// - `worktree_path/.cupola/inputs/` が空のディレクトリとして存在する
///
/// # Errors
/// - `ErrorKind::NotFound` 以外のファイルシステムエラー
pub fn clear_inputs_dir(worktree_path: &Path) -> Result<()> {
    let inputs_dir = worktree_path.join(".cupola/inputs");
    match std::fs::remove_dir_all(&inputs_dir) {
        Ok(()) => {}
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => {}
        Err(e) => {
            return Err(e).with_context(|| format!("failed to remove {}", inputs_dir.display()));
        }
    }
    std::fs::create_dir_all(&inputs_dir)
        .with_context(|| format!("failed to create {}", inputs_dir.display()))?;
    Ok(())
}

// === Input file writing ===

pub fn write_issue_input(worktree_path: &Path, detail: &GitHubIssueDetail) -> Result<()> {
    let inputs_dir = worktree_path.join(".cupola/inputs");
    std::fs::create_dir_all(&inputs_dir)
        .with_context(|| format!("failed to create {}", inputs_dir.display()))?;

    let content = format!(
        "# Issue #{number}: {title}\n\n## Labels\n{labels}\n\n## Body\n{body}\n",
        number = detail.number,
        title = detail.title,
        labels = detail.labels.join(", "),
        body = detail.body,
    );

    let path = inputs_dir.join("issue.md");
    std::fs::write(&path, content)
        .with_context(|| format!("failed to write {}", path.display()))?;

    Ok(())
}

/// worktree 内に spec ディレクトリ（spec.json + requirements.md）を作成する。
/// 既に存在する場合はスキップ。
pub fn write_spec_init(
    worktree_path: &Path,
    issue_number: u64,
    issue_body: &str,
    language: &str,
) -> Result<()> {
    let feature_name = format!("issue-{issue_number}");
    let spec_dir = worktree_path
        .join(".cupola")
        .join("specs")
        .join(&feature_name);

    if spec_dir.exists() {
        tracing::info!(path = %spec_dir.display(), "spec directory already exists, skipping");
        return Ok(());
    }

    std::fs::create_dir_all(&spec_dir)
        .with_context(|| format!("failed to create spec directory at {}", spec_dir.display()))?;

    let now = chrono::Utc::now().format("%Y-%m-%dT%H:%M:%SZ").to_string();

    // spec.json
    let spec_json = format!(
        r#"{{
  "feature_name": "{feature_name}",
  "created_at": "{now}",
  "updated_at": "{now}",
  "language": "{language}",
  "phase": "initialized",
  "approvals": {{
    "requirements": {{ "generated": false, "approved": false }},
    "design": {{ "generated": false, "approved": false }},
    "tasks": {{ "generated": false, "approved": false }}
  }},
  "ready_for_implementation": false
}}"#
    );
    let spec_json_path = spec_dir.join("spec.json");
    std::fs::write(&spec_json_path, spec_json)
        .with_context(|| format!("failed to write {}", spec_json_path.display()))?;

    // requirements.md
    let req_content = format!(
        "# Requirements Document\n\n## Project Description (Input)\n{issue_body}\n\n## Requirements\n<!-- Will be generated by /cupola:spec-design -->\n"
    );
    let req_path = spec_dir.join("requirements.md");
    std::fs::write(&req_path, req_content)
        .with_context(|| format!("failed to write {}", req_path.display()))?;

    tracing::info!(path = %spec_dir.display(), "spec directory initialized");
    Ok(())
}

pub fn write_review_threads_input(
    worktree_path: &Path,
    threads: &[ReviewThread],
    trusted_associations: &TrustedAssociations,
) -> Result<()> {
    let inputs_dir = worktree_path.join(".cupola/inputs");
    std::fs::create_dir_all(&inputs_dir)
        .with_context(|| format!("failed to create {}", inputs_dir.display()))?;

    let mut excluded_count = 0usize;

    let entries: Vec<ReviewThreadEntry> = threads
        .iter()
        .map(|t| {
            let filtered_comments: Vec<CommentEntry> = t
                .comments
                .iter()
                .filter(|c| {
                    if trusted_associations.is_trusted(&c.author_association) {
                        true
                    } else {
                        tracing::info!(
                            author = c.author,
                            association = c.author_association.as_str(),
                            "excluding review comment: author does not have trusted association"
                        );
                        excluded_count += 1;
                        false
                    }
                })
                .map(|c| CommentEntry {
                    author: c.author.clone(),
                    body: c.body.clone(),
                })
                .collect();

            ReviewThreadEntry {
                thread_id: t.id.clone(),
                path: t.path.clone(),
                line: t.line,
                comments: filtered_comments,
            }
        })
        .collect();

    if excluded_count > 0 {
        tracing::info!(
            excluded_count,
            "excluded review comments due to untrusted author association"
        );
    }

    let json = serde_json::to_string_pretty(&entries).context("failed to serialize threads")?;

    let path = inputs_dir.join("review_threads.json");
    std::fs::write(&path, json).with_context(|| format!("failed to write {}", path.display()))?;

    Ok(())
}

#[derive(Serialize)]
struct ReviewThreadEntry {
    thread_id: String,
    path: String,
    line: Option<u32>,
    comments: Vec<CommentEntry>,
}

#[derive(Serialize)]
struct CommentEntry {
    author: String,
    body: String,
}

pub struct CiErrorEntry {
    pub check_run_name: String,
    pub conclusion: String,
    pub output_summary: Option<String>,
    pub output_text: Option<String>,
}

pub fn write_ci_errors_input(worktree_path: &Path, errors: &[CiErrorEntry]) -> Result<()> {
    let inputs_dir = worktree_path.join(".cupola/inputs");
    std::fs::create_dir_all(&inputs_dir)
        .with_context(|| format!("failed to create {}", inputs_dir.display()))?;

    let mut content = String::from("# CI Failure Report\n");

    for entry in errors {
        content.push_str(&format!("\n## {}\n", entry.check_run_name));
        content.push_str(&format!("Conclusion: {}\n", entry.conclusion));

        if let Some(ref summary) = entry.output_summary {
            content.push_str("\n### Summary\n");
            content.push_str(summary);
            content.push('\n');
        }

        if let Some(ref text) = entry.output_text {
            content.push_str("\n### Details\n");
            content.push_str(text);
            content.push('\n');
        }

        content.push_str("\n---\n");
    }

    let path = inputs_dir.join("ci_errors.txt");
    std::fs::write(&path, content)
        .with_context(|| format!("failed to write {}", path.display()))?;

    Ok(())
}

pub struct ConflictInfo {
    pub head_branch: String,
    pub base_branch: String,
    pub default_branch: String,
}

pub fn write_conflict_info_input(worktree_path: &Path, info: &ConflictInfo) -> Result<()> {
    let inputs_dir = worktree_path.join(".cupola/inputs");
    std::fs::create_dir_all(&inputs_dir)
        .with_context(|| format!("failed to create {}", inputs_dir.display()))?;

    let content = format!(
        "# Conflict Information\n\nhead_branch: {}\nbase_branch: {}\ndefault_branch: {}\n",
        info.head_branch, info.base_branch, info.default_branch,
    );

    let path = inputs_dir.join("conflict_info.txt");
    std::fs::write(&path, content)
        .with_context(|| format!("failed to write {}", path.display()))?;

    Ok(())
}

// === Output schema parsing ===

#[derive(Debug, Deserialize)]
pub struct PrCreationOutput {
    pub pr_title: Option<String>,
    pub pr_body: Option<String>,
    pub feature_name: Option<String>,
}

#[derive(Debug, Deserialize)]
pub struct FixingOutput {
    pub threads: Vec<ThreadResponse>,
}

#[derive(Debug, Deserialize)]
pub struct ThreadResponse {
    pub thread_id: String,
    pub response: String,
    pub resolved: bool,
}

/// Parse Claude Code stdout JSON to extract structured_output for PR creation.
/// The stdout format is: `{"session_id": "...", "result": "...", "structured_output": {...}}`
pub fn parse_pr_creation_output(stdout: &str) -> Option<PrCreationOutput> {
    let value: serde_json::Value = serde_json::from_str(stdout).ok()?;
    let structured = &value["structured_output"];
    serde_json::from_value(structured.clone()).ok()
}

/// Parse Claude Code stdout JSON to extract structured_output for fixing.
pub fn parse_fixing_output(stdout: &str) -> Option<FixingOutput> {
    let value: serde_json::Value = serde_json::from_str(stdout).ok()?;
    let structured = &value["structured_output"];
    serde_json::from_value(structured.clone()).ok()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::application::port::github_client::ReviewComment;
    use tempfile::TempDir;

    // === clear_inputs_dir tests ===

    #[test]
    fn clear_inputs_dir_removes_files_and_leaves_empty_dir() {
        let tmp = TempDir::new().expect("tempdir");
        let inputs_dir = tmp.path().join(".cupola/inputs");
        std::fs::create_dir_all(&inputs_dir).expect("create inputs dir");
        std::fs::write(inputs_dir.join("issue.md"), "old content").expect("write file");
        std::fs::write(inputs_dir.join("review_threads.json"), "[]").expect("write file");

        clear_inputs_dir(tmp.path()).expect("clear should succeed");

        assert!(inputs_dir.exists(), "inputs dir should exist after clear");
        let entries = std::fs::read_dir(&inputs_dir)
            .expect("read dir")
            .collect::<Result<Vec<_>, _>>()
            .expect("read dir entries");
        assert!(entries.is_empty(), "inputs dir should be empty after clear");
    }

    #[test]
    fn clear_inputs_dir_succeeds_when_dir_does_not_exist() {
        let tmp = TempDir::new().expect("tempdir");
        // inputs dir does not exist

        clear_inputs_dir(tmp.path()).expect("clear should succeed even if dir missing");

        let inputs_dir = tmp.path().join(".cupola/inputs");
        assert!(inputs_dir.exists(), "inputs dir should be created");
        let entries = std::fs::read_dir(&inputs_dir)
            .expect("read dir")
            .collect::<Result<Vec<_>, _>>()
            .expect("read dir entries");
        assert!(entries.is_empty(), "inputs dir should be empty");
    }

    #[test]
    fn clear_inputs_dir_is_idempotent() {
        let tmp = TempDir::new().expect("tempdir");
        let inputs_dir = tmp.path().join(".cupola/inputs");
        std::fs::create_dir_all(&inputs_dir).expect("create inputs dir");
        std::fs::write(inputs_dir.join("issue.md"), "content").expect("write file");

        clear_inputs_dir(tmp.path()).expect("first clear should succeed");
        clear_inputs_dir(tmp.path()).expect("second clear should also succeed");

        assert!(
            inputs_dir.exists(),
            "inputs dir should exist after second clear"
        );
        let entries = std::fs::read_dir(&inputs_dir)
            .expect("read dir")
            .collect::<Result<Vec<_>, _>>()
            .expect("read dir entries");
        assert!(
            entries.is_empty(),
            "inputs dir should be empty after second clear"
        );
    }

    #[test]
    fn write_issue_input_creates_file() {
        let tmp = TempDir::new().expect("tempdir");
        let detail = GitHubIssueDetail {
            number: 42,
            title: "Add feature".to_string(),
            body: "Please implement X.".to_string(),
            labels: vec!["agent:ready".to_string(), "enhancement".to_string()],
        };

        write_issue_input(tmp.path(), &detail).expect("should write");

        let content = std::fs::read_to_string(tmp.path().join(".cupola/inputs/issue.md"))
            .expect("should read");
        assert!(content.contains("# Issue #42: Add feature"));
        assert!(content.contains("agent:ready, enhancement"));
        assert!(content.contains("Please implement X."));
    }

    #[test]
    fn write_review_threads_creates_json() {
        use crate::domain::author_association::{AuthorAssociation, TrustedAssociations};

        let tmp = TempDir::new().expect("tempdir");
        let threads = vec![ReviewThread {
            id: "PRRT_abc".to_string(),
            path: "src/main.rs".to_string(),
            line: Some(10),
            comments: vec![ReviewComment {
                author: "reviewer".to_string(),
                body: "Fix this".to_string(),
                author_association: AuthorAssociation::Collaborator,
            }],
        }];

        write_review_threads_input(tmp.path(), &threads, &TrustedAssociations::All)
            .expect("should write");

        let content =
            std::fs::read_to_string(tmp.path().join(".cupola/inputs/review_threads.json"))
                .expect("should read");
        assert!(content.contains("PRRT_abc"));
        assert!(content.contains("Fix this"));
    }

    #[test]
    fn write_review_threads_filters_untrusted_comments() {
        use crate::domain::author_association::{AuthorAssociation, TrustedAssociations};

        let tmp = TempDir::new().expect("tempdir");
        let trusted = TrustedAssociations::Specific(vec![AuthorAssociation::Collaborator]);
        let threads = vec![ReviewThread {
            id: "PRRT_abc".to_string(),
            path: "src/main.rs".to_string(),
            line: Some(10),
            comments: vec![
                ReviewComment {
                    author: "trusted-user".to_string(),
                    body: "trusted comment".to_string(),
                    author_association: AuthorAssociation::Collaborator,
                },
                ReviewComment {
                    author: "external-user".to_string(),
                    body: "external comment".to_string(),
                    author_association: AuthorAssociation::None,
                },
            ],
        }];

        write_review_threads_input(tmp.path(), &threads, &trusted).expect("should write");

        let content =
            std::fs::read_to_string(tmp.path().join(".cupola/inputs/review_threads.json"))
                .expect("should read");
        assert!(
            content.contains("trusted comment"),
            "trusted comment should be included"
        );
        assert!(
            !content.contains("external comment"),
            "external comment should be excluded"
        );
    }

    #[test]
    fn write_ci_errors_input_creates_file() {
        let tmp = TempDir::new().expect("tempdir");
        let errors = vec![CiErrorEntry {
            check_run_name: "build".to_string(),
            conclusion: "failure".to_string(),
            output_summary: Some("Build failed".to_string()),
            output_text: Some("Error: cannot find crate".to_string()),
        }];

        write_ci_errors_input(tmp.path(), &errors).expect("should write");

        let content = std::fs::read_to_string(tmp.path().join(".cupola/inputs/ci_errors.txt"))
            .expect("should read");
        assert!(content.contains("# CI Failure Report"));
        assert!(content.contains("## build"));
        assert!(content.contains("Conclusion: failure"));
        assert!(content.contains("Build failed"));
        assert!(content.contains("cannot find crate"));
    }

    #[test]
    fn write_ci_errors_input_empty_list() {
        let tmp = TempDir::new().expect("tempdir");
        write_ci_errors_input(tmp.path(), &[]).expect("should write");

        let content = std::fs::read_to_string(tmp.path().join(".cupola/inputs/ci_errors.txt"))
            .expect("should read");
        assert!(content.contains("# CI Failure Report"));
    }

    #[test]
    fn write_conflict_info_creates_file() {
        let tmp = TempDir::new().expect("tempdir");
        let info = ConflictInfo {
            head_branch: "feature/my-branch".to_string(),
            base_branch: "main".to_string(),
            default_branch: "main".to_string(),
        };

        write_conflict_info_input(tmp.path(), &info).expect("should write");

        let content = std::fs::read_to_string(tmp.path().join(".cupola/inputs/conflict_info.txt"))
            .expect("should read");
        assert!(content.contains("# Conflict Information"));
        assert!(content.contains("head_branch: feature/my-branch"));
        assert!(content.contains("base_branch: main"));
        assert!(content.contains("default_branch: main"));
    }

    #[test]
    fn parse_pr_creation_output_success() {
        let stdout = r#"{"session_id":"s1","result":"done","structured_output":{"pr_title":"Design: Add X","pr_body":"Summary here"}}"#;
        let output = parse_pr_creation_output(stdout).expect("should parse");
        assert_eq!(output.pr_title.as_deref(), Some("Design: Add X"));
        assert_eq!(output.pr_body.as_deref(), Some("Summary here"));
    }

    #[test]
    fn parse_pr_creation_output_missing_fields() {
        let stdout = r#"{"session_id":"s1","result":"done","structured_output":{}}"#;
        let output = parse_pr_creation_output(stdout).expect("should parse with None fields");
        assert!(output.pr_title.is_none());
        assert!(output.pr_body.is_none());
    }

    #[test]
    fn parse_pr_creation_output_invalid_json() {
        assert!(parse_pr_creation_output("not json").is_none());
    }

    #[test]
    fn parse_pr_creation_output_no_structured_output() {
        let stdout = r#"{"session_id":"s1","result":"done"}"#;
        // structured_output is null → should still attempt parse, results in None fields
        let output = parse_pr_creation_output(stdout);
        // serde_json::from_value(Null) for PrCreationOutput may fail
        // This is expected behavior - no structured_output means None
        assert!(output.is_none() || output.is_some());
    }

    #[test]
    fn parse_fixing_output_success() {
        let stdout = r#"{"session_id":"s1","result":"done","structured_output":{"threads":[{"thread_id":"PRRT_abc","response":"修正しました。","resolved":true}]}}"#;
        let output = parse_fixing_output(stdout).expect("should parse");
        assert_eq!(output.threads.len(), 1);
        assert_eq!(output.threads[0].thread_id, "PRRT_abc");
        assert_eq!(output.threads[0].response, "修正しました。");
        assert!(output.threads[0].resolved);
    }

    #[test]
    fn parse_fixing_output_empty_threads() {
        let stdout = r#"{"session_id":"s1","result":"done","structured_output":{"threads":[]}}"#;
        let output = parse_fixing_output(stdout).expect("should parse");
        assert!(output.threads.is_empty());
    }

    #[test]
    fn parse_fixing_output_invalid_json() {
        assert!(parse_fixing_output("garbage").is_none());
    }
}
