use crate::domain::config::Config;
use crate::domain::fixing_problem_kind::FixingProblemKind;
use crate::domain::state::State;

pub struct SessionConfig {
    pub prompt: String,
    pub output_schema: OutputSchemaKind,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum OutputSchemaKind {
    PrCreation,
    Fixing,
}

pub const PR_CREATION_SCHEMA: &str = r#"{"type":"object","properties":{"pr_title":{"type":"string","description":"PR のタイトル"},"pr_body":{"type":"string","description":"PR の body（Markdown 形式）"},"feature_name":{"type":"string","description":"cc-sdd の feature name（.cupola/specs/ 配下のディレクトリ名）"}},"required":["pr_title","pr_body"]}"#;

pub const FIXING_SCHEMA: &str = r#"{"type":"object","properties":{"threads":{"type":"array","items":{"type":"object","properties":{"thread_id":{"type":"string","description":"対応した review thread の ID（PRRT_...）"},"response":{"type":"string","description":"review thread への返信内容"},"resolved":{"type":"boolean","description":"この thread を resolve するか"}},"required":["thread_id","response","resolved"]}}},"required":["threads"]}"#;

pub const GENERIC_QUALITY_CHECK_INSTRUCTION: &str = "commit 前に AGENTS.md / CLAUDE.md に記載された品質チェックを実行し、全てパスしてから commit すること。失敗した場合は修正して再チェックすること。";

pub fn build_session_config(
    state: State,
    issue_number: u64,
    config: &Config,
    pr_number: Option<u64>,
    feature_name: Option<&str>,
    fixing_causes: &[FixingProblemKind],
) -> SessionConfig {
    match state {
        State::DesignRunning => SessionConfig {
            prompt: build_design_prompt(issue_number, &config.language),
            output_schema: OutputSchemaKind::PrCreation,
        },
        State::DesignFixing => {
            let pr = pr_number.expect("fixing state requires pr_number in DB");
            SessionConfig {
                prompt: build_fixing_prompt(issue_number, pr, &config.language, fixing_causes),
                output_schema: OutputSchemaKind::Fixing,
            }
        }
        State::ImplementationRunning => SessionConfig {
            prompt: build_implementation_prompt(issue_number, &config.language, feature_name),
            output_schema: OutputSchemaKind::PrCreation,
        },
        State::ImplementationFixing => {
            let pr = pr_number.expect("fixing state requires pr_number in DB");
            SessionConfig {
                prompt: build_fixing_prompt(issue_number, pr, &config.language, fixing_causes),
                output_schema: OutputSchemaKind::Fixing,
            }
        }
        _ => unreachable!("build_session_config called for non-process state: {state:?}"),
    }
}

pub fn fallback_pr_title(state: State, issue_number: u64) -> String {
    match state {
        State::DesignRunning => format!("Design: Issue #{issue_number}"),
        State::ImplementationRunning => format!("Implement: Issue #{issue_number}"),
        _ => format!("Issue #{issue_number}"),
    }
}

pub fn fallback_pr_body(state: State, issue_number: u64) -> String {
    let relation = match state {
        State::DesignRunning => format!("Related: #{issue_number}"),
        State::ImplementationRunning => format!("Closes #{issue_number}"),
        _ => format!("Related: #{issue_number}"),
    };
    format!("{relation}\n\n---\n🤖 Generated by Cupola via cc-sdd")
}

fn build_design_prompt(issue_number: u64, language: &str) -> String {
    format!(
        r#"あなたは自動設計エージェントです。Issue の内容に基づき、cc-sdd による設計一式を生成してください。

## 入力

Issue の内容は .cupola/inputs/issue.md を参照してください。

## 手順

1. .cupola/inputs/issue.md から Issue の内容を読み取る

2. cc-sdd でスペックを初期化する
   /kiro:spec-init に Issue の概要を渡して実行
   （spec-init が生成する feature name を以降のコマンドで使用すること）

3. 要件定義を生成する
   /kiro:spec-requirements <feature_name>
   Issue 本文の内容を入力として使用すること

4. 設計書を生成する（自動承認）
   /kiro:spec-design <feature_name> -y

5. タスクを生成する（自動承認）
   /kiro:spec-tasks <feature_name> -y

6. {quality_check}

7. 成果物を commit / push する
   git add .cupola/specs/ .cupola/steering/
   git commit -m "docs: add cc-sdd design for #{issue_number}"
   git push

## output-schema への出力

PR の作成はシステム側で行います。以下の情報を出力してください。

- pr_title: 設計 PR のタイトル。"Design: <Issue の要約>" の形式
- pr_body: 設計 PR の body。{language} で記述すること。Related: #{issue_number} を含めること
- feature_name: cc-sdd の feature name（spec-init で生成した .cupola/specs/ 配下のディレクトリ名）

## 制約事項

- 成果物はすべて {language} で記述すること
- GitHub API（gh コマンド含む）は使用しないこと
- PR の作成は行わないこと（システム側で行います）
- PR body で Issue を自動 close するキーワードは使用しないこと（設計 PR は中間成果物のため）"#,
        quality_check = GENERIC_QUALITY_CHECK_INSTRUCTION,
    )
}

fn build_implementation_prompt(
    issue_number: u64,
    language: &str,
    feature_name: Option<&str>,
) -> String {
    let feature_instruction = match feature_name {
        Some(name) => format!(
            "1. cc-sdd による実装を実行する\n   /kiro:spec-impl {name}\n   タスクを TDD で順次実行すること"
        ),
        None => "1. スペックの feature name を確認する\n   ls .cupola/specs/ で feature ディレクトリを特定\n   （複数存在する場合は spec.json の phase が \"tasks-generated\" のものを選択）\n\n2. cc-sdd による実装を実行する\n   /kiro:spec-impl <feature_name>\n   タスクを TDD で順次実行すること".to_string(),
    };

    let (quality_check_step, push_step) = if feature_name.is_some() {
        ("2", "3")
    } else {
        ("3", "4")
    };

    format!(
        r#"あなたは自動実装エージェントです。設計書に基づき、cc-sdd による実装を行ってください。

## 前提

- 現在のブランチに設計成果物が統合されています
- .cupola/specs/ 配下にスペック（requirements.md, design.md, tasks.md）が存在します

## 手順

{feature_instruction}

{quality_check_step}. {quality_check}

{push_step}. 成果物を commit / push する
   最終的に git push

## output-schema への出力

PR の作成はシステム側で行います。以下の情報を出力してください。

- pr_title: 実装 PR のタイトル。"Implement: <Issue の要約>" の形式
- pr_body: 実装 PR の body。{language} で記述すること。Closes #{issue_number} を含めること

## 制約事項

- GitHub API（gh コマンド含む）は使用しないこと
- PR の作成は行わないこと（システム側で行います）"#,
        quality_check = GENERIC_QUALITY_CHECK_INSTRUCTION,
    )
}

fn build_fixing_prompt(
    _issue_number: u64,
    _pr_number: u64,
    language: &str,
    causes: &[FixingProblemKind],
) -> String {
    let mut instructions = Vec::new();

    if causes.contains(&FixingProblemKind::ReviewComments) {
        instructions
            .push(".cupola/inputs/review_threads.json を参照して修正してください".to_string());
    }

    if causes.contains(&FixingProblemKind::CiFailure) {
        instructions.push(".cupola/inputs/ci_errors.txt を参照して修正してください".to_string());
    }

    if causes.contains(&FixingProblemKind::Conflict) {
        instructions.push("PR の base ブランチを取り込んでconflictを解消してください".to_string());
    }

    let instructions_text = if instructions.is_empty() {
        "指摘内容を確認して修正してください".to_string()
    } else {
        instructions
            .iter()
            .enumerate()
            .map(|(i, s)| format!("{}. {s}", i + 1))
            .collect::<Vec<_>>()
            .join("\n")
    };

    format!(
        r#"あなたはレビュー対応エージェントです。以下の指摘事項に対応してください。

## 対応内容

{instructions_text}

## 手順

1. 上記の指摘内容を確認する

2. 必要な修正をコードに反映する

3. {quality_check}

4. 修正を commit / push する
   git add -A
   git commit -m "fix: address review comments"
   git push

## output-schema への出力

コメントの返信と thread の resolve はシステム側で行います。
対応した thread がある場合は各 thread への対応結果を出力してください。

- thread_id: 対応した thread の ID（thread_id をそのまま使用）
- response: その thread への返信内容（{language} で記述）
- resolved: この thread を resolve してよいか（true/false）

## 制約事項

- GitHub API（gh コマンド含む）は使用しないこと
- コメントの返信や thread の resolve は行わないこと（システム側で行います）
- 返信内容はすべて {language} で記述すること"#,
        quality_check = GENERIC_QUALITY_CHECK_INSTRUCTION,
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    fn test_config() -> Config {
        Config::default_with_repo("owner".into(), "repo".into(), "main".into())
    }

    #[test]
    fn design_running_returns_pr_creation_schema() {
        let config = test_config();
        let session = build_session_config(State::DesignRunning, 42, &config, None, None, &[]);
        assert_eq!(session.output_schema, OutputSchemaKind::PrCreation);
        assert!(session.prompt.contains("自動設計エージェント"));
        assert!(session.prompt.contains("#42"));
    }

    #[test]
    fn implementation_running_returns_pr_creation_schema() {
        let config = test_config();
        let session = build_session_config(
            State::ImplementationRunning,
            42,
            &config,
            None,
            Some("my-feature"),
            &[],
        );
        assert_eq!(session.output_schema, OutputSchemaKind::PrCreation);
        assert!(session.prompt.contains("自動実装エージェント"));
    }

    #[test]
    fn design_fixing_returns_fixing_schema() {
        let config = test_config();
        let session = build_session_config(State::DesignFixing, 42, &config, Some(85), None, &[]);
        assert_eq!(session.output_schema, OutputSchemaKind::Fixing);
        assert!(session.prompt.contains("レビュー対応エージェント"));
    }

    #[test]
    fn implementation_fixing_returns_fixing_schema() {
        let config = test_config();
        let session = build_session_config(
            State::ImplementationFixing,
            42,
            &config,
            Some(90),
            None,
            &[],
        );
        assert_eq!(session.output_schema, OutputSchemaKind::Fixing);
    }

    #[test]
    fn fallback_pr_title_for_design() {
        assert_eq!(
            fallback_pr_title(State::DesignRunning, 42),
            "Design: Issue #42"
        );
    }

    #[test]
    fn fallback_pr_title_for_implementation() {
        assert_eq!(
            fallback_pr_title(State::ImplementationRunning, 42),
            "Implement: Issue #42"
        );
    }

    #[test]
    fn fallback_pr_body_for_design() {
        let body = fallback_pr_body(State::DesignRunning, 42);
        assert!(body.contains("Related: #42"));
        assert!(body.contains("Cupola"));
    }

    #[test]
    fn fallback_pr_body_for_implementation() {
        let body = fallback_pr_body(State::ImplementationRunning, 42);
        assert!(body.contains("Closes #42"));
    }

    #[test]
    fn pr_creation_schema_is_valid_json() {
        let _: serde_json::Value =
            serde_json::from_str(PR_CREATION_SCHEMA).expect("should be valid JSON");
    }

    #[test]
    fn design_prompt_contains_related_instruction() {
        let config = test_config();
        let session = build_session_config(State::DesignRunning, 42, &config, None, None, &[]);
        assert!(
            session.prompt.contains("Related: #42"),
            "design prompt should instruct to use 'Related: #N'"
        );
    }

    #[test]
    fn design_prompt_does_not_contain_closes() {
        let config = test_config();
        let session = build_session_config(State::DesignRunning, 42, &config, None, None, &[]);
        assert!(
            !session.prompt.contains("Closes"),
            "design prompt should not contain 'Closes'"
        );
    }

    #[test]
    fn implementation_prompt_contains_closes() {
        let config = test_config();
        let session = build_session_config(
            State::ImplementationRunning,
            42,
            &config,
            None,
            Some("my-feature"),
            &[],
        );
        assert!(
            session.prompt.contains("Closes #42"),
            "implementation prompt should contain 'Closes #42'"
        );
    }

    // Task 7.1: build_fixing_prompt の各パターンのユニットテスト

    #[test]
    fn fixing_prompt_review_comments_only() {
        let config = test_config();
        let session = build_session_config(
            State::DesignFixing,
            42,
            &config,
            Some(85),
            None,
            &[FixingProblemKind::ReviewComments],
        );
        assert!(session.prompt.contains("review_threads.json"));
        assert!(!session.prompt.contains("ci_errors.txt"));
        assert!(!session.prompt.contains("conflict"));
    }

    #[test]
    fn fixing_prompt_ci_failure_only() {
        let config = test_config();
        let session = build_session_config(
            State::DesignFixing,
            42,
            &config,
            Some(85),
            None,
            &[FixingProblemKind::CiFailure],
        );
        assert!(!session.prompt.contains("review_threads.json"));
        assert!(session.prompt.contains("ci_errors.txt"));
        assert!(!session.prompt.contains("conflict"));
    }

    #[test]
    fn fixing_prompt_conflict_only() {
        let config = test_config();
        let session = build_session_config(
            State::DesignFixing,
            42,
            &config,
            Some(85),
            None,
            &[FixingProblemKind::Conflict],
        );
        assert!(!session.prompt.contains("review_threads.json"));
        assert!(!session.prompt.contains("ci_errors.txt"));
        assert!(
            !session.prompt.contains("origin/main"),
            "should not hard-code origin/default_branch"
        );
        assert!(session.prompt.contains("base ブランチ"));
        assert!(session.prompt.contains("conflict"));
    }

    #[test]
    fn fixing_prompt_all_causes() {
        let config = test_config();
        let causes = vec![
            FixingProblemKind::CiFailure,
            FixingProblemKind::Conflict,
            FixingProblemKind::ReviewComments,
        ];
        let session =
            build_session_config(State::DesignFixing, 42, &config, Some(85), None, &causes);
        assert!(session.prompt.contains("review_threads.json"));
        assert!(session.prompt.contains("ci_errors.txt"));
        assert!(
            !session.prompt.contains("origin/main"),
            "should not hard-code origin/default_branch"
        );
        assert!(session.prompt.contains("base ブランチ"));
    }

    #[test]
    fn fixing_schema_is_valid_json() {
        let _: serde_json::Value =
            serde_json::from_str(FIXING_SCHEMA).expect("should be valid JSON");
    }

    #[test]
    fn design_prompt_generic_quality_check() {
        let config = test_config();
        let session = build_session_config(State::DesignRunning, 42, &config, None, None, &[]);
        assert!(
            !session.prompt.contains("cargo"),
            "design prompt should not contain 'cargo'"
        );
        assert!(
            session.prompt.contains(GENERIC_QUALITY_CHECK_INSTRUCTION),
            "design prompt should contain GENERIC_QUALITY_CHECK_INSTRUCTION"
        );
    }

    #[test]
    fn implementation_prompt_generic_quality_check() {
        let config = test_config();
        let session = build_session_config(
            State::ImplementationRunning,
            42,
            &config,
            None,
            Some("my-feature"),
            &[],
        );
        assert!(
            !session.prompt.contains("cargo"),
            "implementation prompt (with feature_name) should not contain 'cargo'"
        );
        assert!(
            session.prompt.contains(GENERIC_QUALITY_CHECK_INSTRUCTION),
            "implementation prompt (with feature_name) should contain GENERIC_QUALITY_CHECK_INSTRUCTION"
        );
    }

    #[test]
    fn implementation_prompt_without_feature_name_generic_quality_check() {
        let config = test_config();
        let session =
            build_session_config(State::ImplementationRunning, 42, &config, None, None, &[]);
        assert!(
            !session.prompt.contains("cargo"),
            "implementation prompt (without feature_name) should not contain 'cargo'"
        );
        assert!(
            session.prompt.contains(GENERIC_QUALITY_CHECK_INSTRUCTION),
            "implementation prompt (without feature_name) should contain GENERIC_QUALITY_CHECK_INSTRUCTION"
        );
    }

    #[test]
    fn fixing_prompt_generic_quality_check() {
        let config = test_config();
        let session = build_session_config(State::DesignFixing, 42, &config, Some(85), None, &[]);
        assert!(
            !session.prompt.contains("cargo"),
            "fixing prompt should not contain 'cargo'"
        );
        assert!(
            session.prompt.contains(GENERIC_QUALITY_CHECK_INSTRUCTION),
            "fixing prompt should contain GENERIC_QUALITY_CHECK_INSTRUCTION"
        );
    }
}
