use anyhow::Context as _;

use crate::domain::config::Config;
use crate::domain::fixing_problem_kind::FixingProblemKind;
use crate::domain::state::State;

#[derive(Debug)]
pub struct SessionConfig {
    pub prompt: String,
    pub output_schema: OutputSchemaKind,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum OutputSchemaKind {
    PrCreation,
    Fixing,
}

pub const PR_CREATION_SCHEMA: &str = r#"{"type":"object","properties":{"pr_title":{"type":"string","description":"Title of the PR"},"pr_body":{"type":"string","description":"Body of the PR (Markdown format)"}},"required":["pr_title","pr_body"]}"#;

pub const FIXING_SCHEMA: &str = r#"{"type":"object","properties":{"threads":{"type":"array","items":{"type":"object","properties":{"thread_id":{"type":"string","description":"ID of the review thread addressed (PRRT_...)"},"response":{"type":"string","description":"Reply content to the review thread"},"resolved":{"type":"boolean","description":"Whether to resolve this thread"}},"required":["thread_id","response","resolved"]}}},"required":["threads"]}"#;

pub const GENERIC_QUALITY_CHECK_INSTRUCTION: &str = "Run quality checks described in AGENTS.md / CLAUDE.md before committing. If any check fails, fix the issues and re-run.";

pub fn build_session_config(
    state: State,
    issue_number: u64,
    config: &Config,
    pr_number: Option<u64>,
    feature_name: &str,
    fixing_causes: &[FixingProblemKind],
) -> anyhow::Result<SessionConfig> {
    match state {
        State::DesignRunning => Ok(SessionConfig {
            prompt: build_design_prompt(issue_number, &config.language, feature_name),
            output_schema: OutputSchemaKind::PrCreation,
        }),
        State::DesignFixing => {
            let pr = pr_number.context("fixing state requires pr_number in DB")?;
            Ok(SessionConfig {
                prompt: build_design_fixing_prompt(
                    issue_number,
                    pr,
                    &config.language,
                    fixing_causes,
                ),
                output_schema: OutputSchemaKind::Fixing,
            })
        }
        State::ImplementationRunning => Ok(SessionConfig {
            prompt: build_implementation_prompt(issue_number, &config.language, feature_name),
            output_schema: OutputSchemaKind::PrCreation,
        }),
        State::ImplementationFixing => {
            let pr = pr_number.context("fixing state requires pr_number in DB")?;
            Ok(SessionConfig {
                prompt: build_implementation_fixing_prompt(
                    issue_number,
                    pr,
                    &config.language,
                    fixing_causes,
                ),
                output_schema: OutputSchemaKind::Fixing,
            })
        }
        _ => unreachable!("build_session_config called for non-process state: {state:?}"),
    }
}

pub fn fallback_pr_title(state: State, issue_number: u64) -> String {
    match state {
        State::DesignRunning => format!("Design: Issue #{issue_number}"),
        State::ImplementationRunning => format!("Implement: Issue #{issue_number}"),
        _ => format!("Issue #{issue_number}"),
    }
}

pub fn fallback_pr_body(state: State, issue_number: u64) -> String {
    let relation = match state {
        State::DesignRunning => format!("Related: #{issue_number}"),
        State::ImplementationRunning => format!("Closes #{issue_number}"),
        _ => format!("Related: #{issue_number}"),
    };
    format!("{relation}\n\n---\n🤖 Generated by Cupola")
}

fn build_design_prompt(issue_number: u64, language: &str, feature_name: &str) -> String {
    format!(
        r#"You are an automated design agent. Generate a complete spec-driven design based on the Issue content.

## Input

- Issue content: .cupola/inputs/issue.md
- Spec directory: .cupola/specs/{feature_name}/ (already initialized with spec.json and requirements.md)

## Steps

1. Run /cupola:spec-design {feature_name}

2. {quality_check}

3. Commit and push the artifacts
   git add .cupola/specs/ .cupola/steering/
   git commit -m "docs: add design for #{issue_number}"
   git push

## Output to output-schema

The PR will be created by the system. Please output the following information.

- pr_title: Title of the design PR. Format: "Design: <Issue summary>"
- pr_body: Body of the design PR. Write in {language}. Include Related: #{issue_number}

## Constraints

- Write all artifacts in {language}
- Do not use the GitHub API (including the gh command)
- Do not create a PR (the system will do it)
- Do not use auto-closing keywords in the PR body (the design PR is an intermediate artifact)"#,
        quality_check = GENERIC_QUALITY_CHECK_INSTRUCTION,
    )
}

fn build_implementation_prompt(issue_number: u64, language: &str, feature_name: &str) -> String {
    format!(
        r#"You are an automated implementation agent. Implement based on the design documents.

## Prerequisites

- The design artifacts have been merged into the current branch
- The spec (requirements.md, design.md, tasks.md) exists under .cupola/specs/{feature_name}/

## Steps

1. Run the implementation
   /cupola:spec-impl {feature_name}
   Execute tasks sequentially using TDD

2. {quality_check}

3. Commit and push the artifacts
   Finally run git push

## Output to output-schema

The PR will be created by the system. Please output the following information.

- pr_title: Title of the implementation PR. Format: "Implement: <Issue summary>"
- pr_body: Body of the implementation PR. Write in {language}. Include Closes #{issue_number}

## Constraints

- Do not use the GitHub API (including the gh command)
- Do not create a PR (the system will do it)"#,
        quality_check = GENERIC_QUALITY_CHECK_INSTRUCTION,
    )
}

fn build_output_section(causes: &[FixingProblemKind], language: &str) -> String {
    if causes.contains(&FixingProblemKind::ReviewComments) {
        format!(
            r#"Comment replies and thread resolution will be handled by the system.
If you addressed any threads, output the result for each thread.

- thread_id: The ID of the thread addressed (use thread_id as-is)
- response: Reply content for that thread (write in {language})
- resolved: Whether this thread should be resolved (true/false)"#
        )
    } else {
        r#"No review thread responses are required for this fix.
Return the following as output:

{"threads": []}"#
            .to_string()
    }
}

fn build_design_fixing_prompt(
    issue_number: u64,
    pr_number: u64,
    language: &str,
    causes: &[FixingProblemKind],
) -> String {
    let output_section = build_output_section(causes, language);

    format!(
        r#"You are an automated review agent. Address the issues on PR #{pr_number} (Issue #{issue_number}).

Run /cupola:fix design

## Output to output-schema

{output_section}

## Constraints

- Do not use the GitHub API (including the gh command)
- Do not reply to comments or resolve threads (the system will do it)
- Write all replies in {language}"#
    )
}

fn build_implementation_fixing_prompt(
    issue_number: u64,
    pr_number: u64,
    language: &str,
    causes: &[FixingProblemKind],
) -> String {
    let output_section = build_output_section(causes, language);

    format!(
        r#"You are an automated review agent. Address the issues on PR #{pr_number} (Issue #{issue_number}).

Run /cupola:fix impl

## Output to output-schema

{output_section}

## Constraints

- Do not use the GitHub API (including the gh command)
- Do not reply to comments or resolve threads (the system will do it)
- Write all replies in {language}"#
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    const FN: &str = "issue-42";

    fn test_config() -> Config {
        Config::default_with_repo("owner".into(), "repo".into(), "main".into())
    }

    #[test]
    fn design_running_returns_pr_creation_schema() {
        let config = test_config();
        let session =
            build_session_config(State::DesignRunning, 42, &config, None, FN, &[]).unwrap();
        assert_eq!(session.output_schema, OutputSchemaKind::PrCreation);
        assert!(session.prompt.contains("automated design agent"));
        assert!(session.prompt.contains("#42"));
        assert!(session.prompt.contains("/cupola:spec-design issue-42"));
    }

    #[test]
    fn implementation_running_returns_pr_creation_schema() {
        let config = test_config();
        let session =
            build_session_config(State::ImplementationRunning, 42, &config, None, FN, &[]).unwrap();
        assert_eq!(session.output_schema, OutputSchemaKind::PrCreation);
        assert!(session.prompt.contains("automated implementation agent"));
        assert!(session.prompt.contains("/cupola:spec-impl issue-42"));
    }

    #[test]
    fn design_fixing_returns_fixing_schema() {
        let config = test_config();
        let session =
            build_session_config(State::DesignFixing, 42, &config, Some(85), FN, &[]).unwrap();
        assert_eq!(session.output_schema, OutputSchemaKind::Fixing);
        assert!(session.prompt.contains("automated review agent"));
    }

    #[test]
    fn implementation_fixing_returns_fixing_schema() {
        let config = test_config();
        let session =
            build_session_config(State::ImplementationFixing, 42, &config, Some(90), FN, &[])
                .unwrap();
        assert_eq!(session.output_schema, OutputSchemaKind::Fixing);
    }

    #[test]
    fn fallback_pr_title_for_design() {
        assert_eq!(
            fallback_pr_title(State::DesignRunning, 42),
            "Design: Issue #42"
        );
    }

    #[test]
    fn fallback_pr_title_for_implementation() {
        assert_eq!(
            fallback_pr_title(State::ImplementationRunning, 42),
            "Implement: Issue #42"
        );
    }

    #[test]
    fn fallback_pr_body_for_design() {
        let body = fallback_pr_body(State::DesignRunning, 42);
        assert!(body.contains("Related: #42"));
        assert!(body.contains("Cupola"));
    }

    #[test]
    fn fallback_pr_body_for_implementation() {
        let body = fallback_pr_body(State::ImplementationRunning, 42);
        assert!(body.contains("Closes #42"));
    }

    #[test]
    fn pr_creation_schema_is_valid_json() {
        let _: serde_json::Value =
            serde_json::from_str(PR_CREATION_SCHEMA).expect("should be valid JSON");
    }

    #[test]
    fn design_prompt_contains_related_instruction() {
        let config = test_config();
        let session =
            build_session_config(State::DesignRunning, 42, &config, None, FN, &[]).unwrap();
        assert!(
            session.prompt.contains("Related: #42"),
            "design prompt should instruct to use 'Related: #N'"
        );
    }

    #[test]
    fn design_prompt_does_not_contain_closes() {
        let config = test_config();
        let session =
            build_session_config(State::DesignRunning, 42, &config, None, FN, &[]).unwrap();
        assert!(
            !session.prompt.contains("Closes"),
            "design prompt should not contain 'Closes'"
        );
    }

    #[test]
    fn design_prompt_does_not_contain_legacy_namespace() {
        let config = test_config();
        let session =
            build_session_config(State::DesignRunning, 42, &config, None, FN, &[]).unwrap();
        let legacy_namespace = ["/", "k", "i", "r", "o", ":"].concat();
        assert!(
            !session.prompt.contains(&legacy_namespace),
            "design prompt should not contain legacy namespace references"
        );
    }

    #[test]
    fn implementation_prompt_contains_closes() {
        let config = test_config();
        let session =
            build_session_config(State::ImplementationRunning, 42, &config, None, FN, &[]).unwrap();
        assert!(
            session.prompt.contains("Closes #42"),
            "implementation prompt should contain 'Closes #42'"
        );
    }

    #[test]
    fn implementation_prompt_does_not_contain_legacy_namespace() {
        let config = test_config();
        let session =
            build_session_config(State::ImplementationRunning, 42, &config, None, FN, &[]).unwrap();
        let legacy_namespace = ["/", "k", "i", "r", "o", ":"].concat();
        assert!(
            !session.prompt.contains(&legacy_namespace),
            "implementation prompt should not contain legacy namespace references"
        );
    }

    // --- Existing fixing_prompt_* tests ---

    #[test]
    fn fixing_prompt_review_comments_only() {
        let config = test_config();
        for state in [State::DesignFixing, State::ImplementationFixing] {
            let session = build_session_config(
                state,
                42,
                &config,
                Some(85),
                FN,
                &[FixingProblemKind::ReviewComments],
            )
            .unwrap();
            assert!(session.prompt.contains("PR #85"));
            assert!(session.prompt.contains("Issue #42"));
        }
    }

    #[test]
    fn fixing_prompt_ci_failure_only() {
        let config = test_config();
        for state in [State::DesignFixing, State::ImplementationFixing] {
            let session = build_session_config(
                state,
                42,
                &config,
                Some(85),
                FN,
                &[FixingProblemKind::CiFailure],
            )
            .unwrap();
            assert!(session.prompt.contains("PR #85"));
            assert!(session.prompt.contains("Issue #42"));
            assert!(session.prompt.contains(r#"{"threads": []}"#));
            assert!(!session.prompt.contains("thread_id"));
        }
    }

    #[test]
    fn fixing_prompt_conflict_only() {
        let config = test_config();
        for state in [State::DesignFixing, State::ImplementationFixing] {
            let session = build_session_config(
                state,
                42,
                &config,
                Some(85),
                FN,
                &[FixingProblemKind::Conflict],
            )
            .unwrap();
            assert!(session.prompt.contains("PR #85"));
            assert!(session.prompt.contains("Issue #42"));
            assert!(session.prompt.contains(r#"{"threads": []}"#));
            assert!(!session.prompt.contains("thread_id"));
        }
    }

    #[test]
    fn fixing_prompt_all_causes() {
        let config = test_config();
        let causes = vec![
            FixingProblemKind::CiFailure,
            FixingProblemKind::Conflict,
            FixingProblemKind::ReviewComments,
        ];
        for state in [State::DesignFixing, State::ImplementationFixing] {
            let session = build_session_config(state, 42, &config, Some(85), FN, &causes).unwrap();
            assert!(session.prompt.contains("PR #85"));
            assert!(session.prompt.contains("Issue #42"));
            assert!(session.prompt.contains("thread_id"));
            assert!(!session.prompt.contains(r#"{"threads": []}"#));
        }
    }

    #[test]
    fn fixing_prompt_no_git_add_all() {
        let config = test_config();

        for state in [State::DesignFixing, State::ImplementationFixing] {
            for cause in [
                vec![FixingProblemKind::ReviewComments],
                vec![FixingProblemKind::CiFailure],
                vec![FixingProblemKind::Conflict],
                vec![
                    FixingProblemKind::CiFailure,
                    FixingProblemKind::Conflict,
                    FixingProblemKind::ReviewComments,
                ],
            ] {
                let session =
                    build_session_config(state, 42, &config, Some(85), FN, &cause).unwrap();
                assert!(
                    !session.prompt.contains("git add -A"),
                    "prompt should not contain 'git add -A'"
                );
            }
        }
    }

    #[test]
    fn design_fixing_without_pr_number_returns_err() {
        let config = test_config();
        let result = build_session_config(State::DesignFixing, 42, &config, None, FN, &[]);
        assert!(result.is_err());
        assert!(
            result
                .unwrap_err()
                .to_string()
                .contains("fixing state requires pr_number in DB")
        );
    }

    #[test]
    fn implementation_fixing_without_pr_number_returns_err() {
        let config = test_config();
        let result = build_session_config(State::ImplementationFixing, 42, &config, None, FN, &[]);
        assert!(result.is_err());
        assert!(
            result
                .unwrap_err()
                .to_string()
                .contains("fixing state requires pr_number in DB")
        );
    }

    #[test]
    fn design_running_without_pr_number_returns_ok() {
        let config = test_config();
        let result = build_session_config(State::DesignRunning, 42, &config, None, FN, &[]);
        assert!(result.is_ok());
    }

    #[test]
    fn fixing_schema_is_valid_json() {
        let _: serde_json::Value =
            serde_json::from_str(FIXING_SCHEMA).expect("should be valid JSON");
    }

    #[test]
    fn design_prompt_generic_quality_check() {
        let config = test_config();
        let session =
            build_session_config(State::DesignRunning, 42, &config, None, FN, &[]).unwrap();
        assert!(session.prompt.contains(GENERIC_QUALITY_CHECK_INSTRUCTION));
    }

    #[test]
    fn implementation_prompt_generic_quality_check() {
        let config = test_config();
        let session =
            build_session_config(State::ImplementationRunning, 42, &config, None, FN, &[]).unwrap();
        assert!(session.prompt.contains(GENERIC_QUALITY_CHECK_INSTRUCTION));
    }

    #[test]
    fn design_fixing_no_git_add_all() {
        let config = test_config();
        for cause in [
            vec![FixingProblemKind::ReviewComments],
            vec![FixingProblemKind::CiFailure],
            vec![FixingProblemKind::Conflict],
        ] {
            let session =
                build_session_config(State::DesignFixing, 42, &config, Some(85), FN, &cause)
                    .unwrap();
            assert!(
                !session.prompt.contains("git add -A"),
                "DesignFixing prompt should not contain 'git add -A'"
            );
        }
    }

    // --- Task 4.2: スキル委譲テスト ---

    #[test]
    fn design_fixing_prompt_delegates_to_fix_skill() {
        let config = test_config();
        let session =
            build_session_config(State::DesignFixing, 42, &config, Some(85), FN, &[]).unwrap();
        assert!(
            session.prompt.contains("Run /cupola:fix design"),
            "DesignFixing prompt should delegate to /cupola:fix design"
        );
    }

    #[test]
    fn implementation_fixing_prompt_delegates_to_fix_skill() {
        let config = test_config();
        let session =
            build_session_config(State::ImplementationFixing, 42, &config, Some(90), FN, &[])
                .unwrap();
        assert!(
            session.prompt.contains("Run /cupola:fix impl"),
            "ImplementationFixing prompt should delegate to /cupola:fix impl"
        );
    }

    #[test]
    fn design_fixing_prompt_has_no_inline_steps() {
        let config = test_config();
        let session =
            build_session_config(State::DesignFixing, 42, &config, Some(85), FN, &[]).unwrap();
        assert!(
            !session.prompt.contains("git commit -m"),
            "DesignFixing prompt should not contain inline git commit instructions"
        );
        assert!(
            !session.prompt.contains("git add "),
            "DesignFixing prompt should not contain inline git add instructions"
        );
    }

    #[test]
    fn implementation_fixing_prompt_has_no_inline_steps() {
        let config = test_config();
        let session =
            build_session_config(State::ImplementationFixing, 42, &config, Some(90), FN, &[])
                .unwrap();
        assert!(
            !session.prompt.contains("git commit -m"),
            "ImplementationFixing prompt should not contain inline git commit instructions"
        );
        assert!(
            !session.prompt.contains("git add "),
            "ImplementationFixing prompt should not contain inline git add instructions"
        );
    }
}
